package before_resolution

import rego.v1

# Every bounded error code must have an exact event definition for the
# correlated log name generated by the application.
deny contains exception_finding(
	"missing_exception_event",
	member.value,
	sprintf("nwsl.%s.exception", [member.value]),
	"NWSL error codes must have a matching correlated exception event",
) if {
	group := input.groups[_]
	attr := group.attributes[_]
	attr.id == "nwsl.error.code"
	member := attr.type.members[_]
	event_name := sprintf("nwsl.%s.exception", [member.value])
	not has_exception_event(input.groups, event_name)
}

# Keep the inverse true as well so removing or renaming an error code cannot
# leave a documented event that the generated code can no longer select.
deny contains exception_finding(
	"orphaned_exception_event",
	"",
	event.name,
	"NWSL exception events must have a matching error code",
) if {
	event := input.groups[_]
	event.type == "event"
	startswith(event.name, "nwsl.")
	endswith(event.name, ".exception")
	not has_error_code_event(input.groups, event.name)
}

has_exception_event(groups, event_name) if {
	event := groups[_]
	event.type == "event"
	event.name == event_name
}

has_error_code_event(groups, event_name) if {
	group := groups[_]
	attr := group.attributes[_]
	attr.id == "nwsl.error.code"
	member := attr.type.members[_]
	event_name == sprintf("nwsl.%s.exception", [member.value])
}

exception_finding(finding_id, error_code, event_name, message) := {
	"id": finding_id,
	"context": {
		"id": "nwsl_exception_event_governance",
		"error_code": error_code,
		"event": event_name,
	},
	"message": sprintf("%s: %s", [message, event_name]),
	"level": "violation",
}
